name: Build

# Triggers the workflow on push or pull request events (for any branch in a repository)
on: [ push, pull_request ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
          - nightly
          - 1.64.0 # MSVR of the CLI binary
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: default
          toolchain: ${{ matrix.rust }}
          override: true
      - name: Build
        run: cargo build --all-targets --features bin --verbose

  library_msrv:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: default
          toolchain: 1.57.0 # MSRV of library
          override: true
      - name: Build Lib as Dependency with MSRV
        run: cd ttfb-lib-msrv-check && cargo build --all-targets --verbose

  tests:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: default
          # Sufficient to execute tessts only with this version
          # as we built them in the build-step with multiple versions.
          toolchain: stable
          override: true
      - name: Build
        run: cargo test --all-targets --verbose

  network-tests:
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: default
          # Sufficient to execute tessts only with this version
          # as we built them in the build-step with multiple versions.
          toolchain: stable
          override: true
      - name: Run tests
        run: RUSTFLAGS="--cfg network_tests" cargo test --verbose

  style_checks:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: default
          toolchain: ${{ matrix.rust }}
          override: true
      - name: Rustfmt
        run: cargo fmt -- --check
      - name: Clippy
        run: cargo clippy --all-targets
      - name: Rustdoc
        run: cargo doc --document-private-items
